- docs/AboutUs.md
- docs/team/xueting.md
Update xueting in about us, add xueting.md
> Update xueting about us

- README.md
A3. Acknowledge the original source of the code e.g.,
A4. Update all remaining contents of the page to match your own project.
> Branch zwe update readme

- src/main/java/seedu/address/logic/validator/NameValidator.java
- src/main/java/seedu/address/logic/validator/RoleValidator.java
- src/main/java/seedu/address/model/internshipapplication/Date.java
- src/main/java/seedu/address/model/internshipapplication/Role.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/testutil/TypicalInternshipApplications.java
Closes [Fix commands failing tests](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/72)
Fixes the failing tests in the commands package.
> Update test cases for commands package

- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/Parser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/testutil/InternshipApplicationBuilder.java
- src/test/java/seedu/address/testutil/InternshipApplicationUtil.java
- src/test/java/seedu/address/testutil/TypicalInternshipApplications.java
Closes [Fix parser failing tests #80](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/80)
Fixes failing parser tests. Also removed the use of "c/" as a command because it is not useful and complicates things. Furthermore, since company name is a name object, it has been replacd with "n/" as it makes more sense
Previously an internship application can be added via using "c/" for company name. However, it has been changed to use "n/" for company name
Run the automated parser tests
> Fix failing parser tests

- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
Closes [More failing test#85](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/85)
Fixed last few tests
> Fix more tests

- src/main/java/seedu/address/logic/validator/DateValidator.java
Closes [Fix DateValidator bug#91](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/91)
Fixes the bug where the application allows for invalid date.
Changes the DateTimeFormatter in DateValidator to use a STRICT ResolverStyle.
> Fix DateValidator bug

- src/main/java/seedu/hireme/logic/validator/NameValidator.java
- src/main/java/seedu/hireme/logic/validator/StatusValidator.java
- src/main/java/seedu/hireme/model/internshipapplication/InternshipApplication.java
- src/main/java/seedu/hireme/model/internshipapplication/Status.java
- src/main/java/seedu/hireme/storage/JsonAdaptedInternship.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
- src/test/java/seedu/hireme/storage/JsonAdaptedInternshipTest.java
- src/test/java/seedu/hireme/testutil/InternshipApplicationBuilder.java
Closes [Add Status feature #104](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/104)
Adds status feature and maintain integrity of test cases.
> Add status feature

- src/main/java/seedu/hireme/storage/JsonAddressBookStorage.java
- src/test/java/seedu/hireme/logic/LogicManagerTest.java
- src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/hireme/logic/parser/ArgumentTokenizerTest.java
- src/test/java/seedu/hireme/logic/parser/DeleteCommandParserTest.java
- src/test/java/seedu/hireme/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/hireme/storage/JsonAddressBookStorageTest.java
- src/test/java/seedu/hireme/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/hireme/storage/JsonUserPrefsStorageTest.java
- src/test/java/seedu/hireme/storage/StorageManagerTest.java
Closes [Update tests for storage and parser #113](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/113)
- Added defensive programming to test cases by applying `isPresent` on `Optional` objects.
- Added missing test cases
- Minor code refactoring
> Update tests for storage and parser

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/NewDiagram.puml
Resolves Update UML Diagram #122 (https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/122)
> Update UML Diagram

- src/main/java/seedu/hireme/model/ModelManager.java
- src/main/java/seedu/hireme/storage/StorageManager.java
- src/test/java/seedu/hireme/storage/StorageManagerTest.java
Closes [Add more logging #124](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/124)
> Add more logging

- build.gradle
- src/main/java/seedu/hireme/commons/core/Config.java
- src/main/java/seedu/hireme/commons/core/GuiSettings.java
- src/main/java/seedu/hireme/commons/core/LogsCenter.java
- src/main/java/seedu/hireme/commons/util/ConfigUtil.java
- src/main/java/seedu/hireme/commons/util/FileUtil.java
- src/main/java/seedu/hireme/model/internshipapplication/Email.java
- src/test/java/seedu/hireme/commons/core/ConfigTest.java
- src/test/java/seedu/hireme/commons/core/GuiSettingsTest.java
- src/test/java/seedu/hireme/commons/core/VersionTest.java
- src/test/java/seedu/hireme/commons/core/index/IndexTest.java
- src/test/java/seedu/hireme/commons/util/AppUtilTest.java
- src/test/java/seedu/hireme/commons/util/CollectionUtilTest.java
- src/test/java/seedu/hireme/commons/util/ConfigUtilTest.java
- src/test/java/seedu/hireme/commons/util/FileUtilTest.java
- src/test/java/seedu/hireme/commons/util/JsonUtilTest.java
- src/test/java/seedu/hireme/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/hireme/logic/commands/AddCommandTest.java
- src/test/java/seedu/hireme/logic/commands/ClearCommandTest.java
- src/test/java/seedu/hireme/logic/commands/CommandResultTest.java
- src/test/java/seedu/hireme/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/hireme/logic/commands/FindCommandTest.java
- src/test/java/seedu/hireme/logic/commands/ListCommandTest.java
Closes [Update tests for commons and commands #114](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/114)
Updates the test cases for classes in commons and commands package.
Changed the test cases for FindCommand to comply with the specificity of the command.
FindCommand predicate is "contains" instead of "exact match".
> Update tests for commons and commands

- src/main/java/seedu/hireme/ui/InternshipApplicationCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/InternshipApplicationListCard.fxml
Closes [Add UI to show statuses #134](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/134)
Adds colour coded fields to the UI to have better visuals on the statuses of applications.
> Add ui to show statuses

- src/main/java/seedu/hireme/logic/commands/StatusCommand.java
- src/main/java/seedu/hireme/logic/parser/ParserUtil.java
- src/main/java/seedu/hireme/logic/validator/DateValidator.java
- src/main/java/seedu/hireme/model/internshipapplication/Date.java
- src/main/java/seedu/hireme/ui/InternshipApplicationCard.java
- src/main/resources/view/InternshipApplicationListCard.fxml
Closes [Fix Filter's bug that resets the UI's list after Status commands #140](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/140)
Closes [Fix bug that does not allow today's date as input #139](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/139)
Closes [Fix wrong error message when too many arguments passed in #138](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/138)
Closes [Fix delay in showing UI status #136](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/136)
- Previously, Status commands finds the InternshipApplication to be updated and updates it directly. It has been updated to created a new InternshipApplication with the updated status and utilise `Model::setItem` to edit the FilteredList instead. It then calls `Model::updateFilteredList` to update the …
> Fix UI bugs regarding Status and Date

- src/main/java/seedu/hireme/commons/util/StringUtil.java
- src/main/java/seedu/hireme/logic/parser/SortCommandParser.java
- src/main/java/seedu/hireme/logic/validator/EmailValidator.java
- src/main/java/seedu/hireme/logic/validator/NameValidator.java
- src/main/java/seedu/hireme/logic/validator/RoleValidator.java
- src/main/java/seedu/hireme/logic/validator/StatusValidator.java
- src/main/java/seedu/hireme/ui/InsightsWindow.java
- src/main/resources/view/InsightsWindow.css
- src/test/java/seedu/hireme/commons/util/StringUtilTest.java
Closes [Insights Bug: colour is not consistent. #152](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/152)
The colours of the pie chart no longer rotate upon reopening the insights window. The labels of the pie chart also no longer overlap with one another
The colours of the pie chart are fixed according to the status colours.
The labels of the pie chart will be at their respective positions.
Percentages are added to give users better insights
Added tests for percentage conversion
1. Type in /insights command
2. Close the window and type in the same command again
> Fix insights bugs

- src/main/java/seedu/hireme/logic/Messages.java
- src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
- src/main/java/seedu/hireme/logic/commands/StatusCommand.java
- src/main/java/seedu/hireme/logic/parser/DeleteCommandParser.java
- src/test/java/seedu/hireme/commons/util/StringUtilTest.java
- src/test/java/seedu/hireme/logic/LogicManagerTest.java
- src/test/java/seedu/hireme/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/hireme/logic/commands/StatusCommandTest.java
Closes [Delete bug: Need to have better error message #156](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/156)
Ensure the error message shown on invalid delete and status commands are consistent
Improved error message consistency
Ensured tests use these new error messages
1. Automated tests can be run
> Fix inconsistent error message

- src/main/java/seedu/hireme/logic/commands/AddCommand.java
- src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
- src/main/java/seedu/hireme/logic/commands/FindCommand.java
- src/main/java/seedu/hireme/logic/commands/StatusCommand.java
- src/main/java/seedu/hireme/logic/parser/ParserUtil.java
- src/main/java/seedu/hireme/logic/validator/StatusValidator.java
- src/main/java/seedu/hireme/model/internshipapplication/Status.java
- src/main/java/seedu/hireme/storage/JsonAdaptedInternship.java
- src/test/java/seedu/hireme/logic/LogicManagerTest.java
- src/test/java/seedu/hireme/logic/parser/ParserUtilTest.java
- src/test/java/seedu/hireme/testutil/InternshipApplicationBuilder.java
Closes [Change command words to full form instead of short form #127](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/127), [Allow Status to be case insensitive #190](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/190)
Changes all command words to be of full form.
Creates a new static method `Status::createStatus` to allow case-insensitive status input.
This methods bypasses having to call `toUpper()` on all status `String` input
> Change all commands to full form

- docs/UserGuide.md
Closes [Update FAQ portion for UG #195](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/195)
> Branch dylan update ug

- docs/DeveloperGuide.md
- docs/diagrams/DeleteSequenceDiagram.puml
- docs/diagrams/HelpSequenceDiagram.puml
- src/test/java/seedu/hireme/logic/validator/StatusValidatorTest.java
Added help sequence diagram
Updated delete sequence diagram
Added use case extensions for sort
Added manual testing explanation for sort
> Update developer guide

- src/main/java/seedu/hireme/logic/commands/AddCommand.java
- src/main/java/seedu/hireme/model/internshipapplication/Role.java
- Update error message for invalid role field
- Update error message for duplicate internship applications
> Update error msg

- docs/DeveloperGuide.md
- src/main/resources/view/Extensions.css
- src/main/resources/view/HireMeTheme.css
Closes #209, #210
The issues are about UI bugs and DG improvements
Fixes UI bugs, and improve on DG's filter section and use cases.
- Changed background to white, changed status label text to white.
- Update phrasing in filter section in DG
- Add exit use case
- Add index to glossary
Improve on DG and UI. UI cannot be changed after 1.5 so need to check if it fixes
1. Check if the black background still shows when the list has only one application
> Fix UI bugs and update DG 

- src/main/java/seedu/hireme/logic/commands/ClearCommand.java
- src/test/java/seedu/hireme/logic/commands/ClearCommandTest.java
Closes [Clear command to update chart #213](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/213)
- Changed clear command to update pie chart if chart is already opened
- Updated clear tests
> Clear to update chart

- docs/team/raghava-chittidi.md
- docs/team/zwezeya.md
Updated about me page
1. Navigate to https://ay2425s1-cs2103t-w09-3.github.io/tp/team/raghava-chittidi.html
> Update about me

- README.md
- docs/DeveloperGuide.md
- docs/index.md
- Added manual testing notes for chart, list, clear, filter commands
- Update badge links in readme and docs
> Branch docs

- src/main/java/seedu/hireme/logic/commands/StatusCommand.java
Ensure consistency in error messages for command
> Update error message

- docs/UserGuide.md
> Fix UG ToC

- docs/team/xueting.md
- fix bugs in xueting about us
Fix bugs in xueting portfolio
> Fix about us xueting md

- docs/AboutUs.md
- docs/team/choaticman.md
> Update about us page

- docs/DeveloperGuide.md
- Reformat Manual Testing Section
> Reformat manual testing section

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/ExitSequenceDiagram.puml
Fix exit diagram inconsistency
Added extra line breaks to ensure better formatting
> Fix bug in docs

- docs/DeveloperGuide.md
- docs/diagrams/ClearSequenceDiagram.puml
- Add clear in implementation
Clear sequence diagram
Add clear implementation and fix TOC
> Add clear sequence diagram

- src/main/java/seedu/hireme/MainApp.java
> Update version to v1.5

- docs/UserGuide.md
> Add welcome message in UG

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/FindSequenceDiagram.puml
Closes #308, #306, #301, #294 
- Fix `Find` Sequence Diagram
- Include example of `/filter pending` followed by `/accept 1` to inform user that the application will not be shown on the list on the application.
- Include line breaks to DG's manual testing section to improve readability.
- Update Date's range in UG from `2000 to 2099` to `2000 to the current year`
> Fix v1.6 bugs

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/ExitSequenceDiagram.puml
Closes the following issues:
- [#278](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/278)
- [#274](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/274)
- [#263](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/263)
- [#251](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/251)
- [#238](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/238)
- [#299](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/299)
- [#304](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/304)
- [#305](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/305)
- [#311](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/311)
- Updated sequence diagram for exit
- Fixed typo in `chart` manual testing
- Added extension for `add` UC
- Added extensions for UC for commands without arguments
- Added FAQ …
> Doc bugs from PE-D

- docs/UserGuide.md
- docs/_markbind/layouts/default.md
Fix images being cut off in the ug due to width being too large
Added extra link in sitemap
> Fix images and sitemap

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/StatusActivityDiagram.puml
Closes #309, #295, #287, #259, #256, #245, #261, #297
This PR resolves overlapping text and line issues in activity diagrams, clarifies use case steps by removing unnecessary details, corrects function invocations in UML diagrams, and updates the docs to specify the error messages for invalid commands.
| Previous Behavior | Updated Behavior |
|--------------------|------------------|
| Text and lines overlapped, reducing readability. | Updated diagrams to have clear, non-overlapping elements. |
| Font size was too small to read comfortably. | Adjusted font size for better readability. |
| Redundant step included in use case, potentially confusing users. | Removed unnecessary step, streamlining the use case. |
| Lacked detailed function calls in UML diagrams. | Added in DG that the …
> Fix UG and DG bugs

- docs/DeveloperGuide.md
- Changed `argument` to `parameter` in DG
> Change argument to parameter in DG

- docs/UserGuide.md
Closes [#286](https://github.com/AY2425S1-CS2103T-W09-3/tp/issues/286)
- change `must` to `can`
> Change add guide in ug

- docs/UserGuide.md
- fix bugs in setting up
Fix setting up bugs 
1. Navigate to setting up in UG
> Fix setting up bugs

- docs/UserGuide.md
- Changed definition of duplicate
- Formatting error
> Change duplicate defn

- docs/UserGuide.md
- add more terms to glossary
Add technical terms to glossary
1. Navigate to glossary in UG
> Add to glossary

- docs/UserGuide.md
- docs/_markbind/layouts/default.md
Fix small typos, add acknowledgements
> Fix ug final changes

- docs/UserGuide.md
Add code block and fix definitions
> Add code block

- src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
- src/main/resources/view/MainWindow.fxml
- src/test/java/seedu/hireme/commons/core/index/IndexTest.java
- src/test/java/seedu/hireme/logic/commands/AddCommandTest.java
- src/test/java/seedu/hireme/logic/commands/CommandTestUtil.java
- src/test/java/seedu/hireme/logic/commands/FindCommandTest.java
- src/test/java/seedu/hireme/model/AddressBookTest.java
- src/test/java/seedu/hireme/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/hireme/testutil/AddressBookBuilder.java
> Fix delete error message

- docs/DeveloperGuide.md
> Minor DG Fixes

- docs/DeveloperGuide.md
Closes #302 
Closes #300 
Closes #298 
Closes #291 
Closes #272 
Closes #262 
Closes #252 
Closes #249 
Closes #244 
- Add planned enhancements to address certain issues.
> Add points to planned enhancements

- docs/DeveloperGuide.md
- Add additional formatting for planned enhancement segment.
> Add additional formatting

- docs/DeveloperGuide.md
Imroved formatting and explanation for error message enhancement
> Improve error message enhancement

- docs/DeveloperGuide.md
> Add indentation

- docs/DeveloperGuide.md
> Add enchancements

- docs/DeveloperGuide.md
Add formatting to UI planned enhancement
1. Navigate to planned enhancement
> Improve UI planned enhancement

- docs/DeveloperGuide.md
- docs/_markbind/layouts/default.md
- Format enhancements
- Other format changes
> Fix DG Bugs

- docs/DeveloperGuide.md
> Minor fixes to DG
